Revert bugfix for weekly alias always being created
This reverts part of f7e1a9bacbde4d291041943c4ba92c7598c54380
because it's causing the error below. Once we figure out the cause we'll
reintroduce this bugfix. This leaves the new get_aliases method in mozdef_util
in place as it's fine (though we're not actually calling it for some reason)

```
Connecting to http://elasticsearch:9200
Traceback (most recent call last):
 File "initial_setup.py", line 61, in <module>
   'events,events-previous,alerts,events-weekly')
 File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
   return func(*args, params=params, **kwargs)
 File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 399, in get_alias
   '_alias', name), params=params)
 File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
   status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
 File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
   self._raise_error(response.status, raw_data)
 File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
   raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, u'index_not_found_exception', u'no such index')
```